'use client';

import { useEffect, useState } from 'react';

type Voucher = { id: string; code: string; discountType: string; discountValue: number; minOrderAmount: number; usedCount: number; usageLimit: number | null; isActive: boolean };
type Combo = { id: string; name: string; price: number; stock: number; isActive: boolean };

export function VoucherManagement() {
  const [items, setItems] = useState<Voucher[]>([]);
  const [form, setForm] = useState({ code: '', discountType: 'FIXED', discountValue: '50000', minOrderAmount: '0', usageLimit: '', perUserLimit: '1', startsAt: new Date().toISOString().slice(0, 16), endsAt: new Date(Date.now() + 30 * 86400000).toISOString().slice(0, 16) });
  const load = async () => setItems(await (await fetch('/api/admin/vouchers')).json());
  useEffect(() => { void load(); }, []);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); await fetch('/api/admin/vouchers', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); setForm((current) => ({ ...current, code: '' })); await load(); };
  return <div className="space-y-6"><form onSubmit={submit} className="grid gap-3 rounded-2xl border border-white/10 bg-white/5 p-4 md:grid-cols-4">{[['code','Mã voucher'],['discountValue','Mức giảm'],['minOrderAmount','Đơn tối thiểu'],['usageLimit','Tổng lượt']].map(([name, label]) => <label key={name} className="text-sm text-slate-300">{label}<input name={name} value={form[name as keyof typeof form]} onChange={(event) => setForm({ ...form, [name]: event.target.value })} className="mt-1 w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2 text-white" /></label>)}<label className="text-sm text-slate-300">Loại<select value={form.discountType} onChange={(event) => setForm({ ...form, discountType: event.target.value })} className="mt-1 w-full rounded-xl bg-slate-950 px-3 py-2 text-white"><option value="FIXED">Số tiền</option><option value="PERCENT">Phần trăm</option></select></label><label className="text-sm text-slate-300">Bắt đầu<input type="datetime-local" value={form.startsAt} onChange={(event) => setForm({ ...form, startsAt: event.target.value })} className="mt-1 w-full rounded-xl bg-slate-950 px-3 py-2 text-white" /></label><label className="text-sm text-slate-300">Kết thúc<input type="datetime-local" value={form.endsAt} onChange={(event) => setForm({ ...form, endsAt: event.target.value })} className="mt-1 w-full rounded-xl bg-slate-950 px-3 py-2 text-white" /></label><button className="rounded-xl bg-sky-500 px-4 py-2 font-semibold text-white">Tạo voucher</button></form><div className="grid gap-3">{items.map((item) => <div key={item.id} className="flex flex-wrap justify-between gap-3 rounded-2xl border border-white/10 p-4 text-sm text-slate-300"><b className="text-white">{item.code}</b><span>{item.discountType === 'PERCENT' ? `${item.discountValue}%` : `${item.discountValue.toLocaleString('vi-VN')} đ`}</span><span>Đã dùng {item.usedCount}{item.usageLimit ? `/${item.usageLimit}` : ''}</span><span>{item.isActive ? 'Đang bật' : 'Đã tắt'}</span></div>)}</div></div>;
}

export function ComboManagement() {
  const [items, setItems] = useState<Combo[]>([]);
  const [form, setForm] = useState({ name: '', description: '', price: '79000', stock: '0' });
  const load = async () => setItems(await (await fetch('/api/admin/combos')).json());
  useEffect(() => { void load(); }, []);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); await fetch('/api/admin/combos', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); setForm({ name: '', description: '', price: '79000', stock: '0' }); await load(); };
  return <div className="space-y-6"><form onSubmit={submit} className="grid gap-3 rounded-2xl border border-white/10 bg-white/5 p-4 md:grid-cols-4"><input required placeholder="Tên combo" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className="rounded-xl bg-slate-950 px-3 py-2 text-white" /><input placeholder="Mô tả" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} className="rounded-xl bg-slate-950 px-3 py-2 text-white" /><input type="number" placeholder="Giá" value={form.price} onChange={(event) => setForm({ ...form, price: event.target.value })} className="rounded-xl bg-slate-950 px-3 py-2 text-white" /><button className="rounded-xl bg-sky-500 px-4 py-2 font-semibold text-white">Thêm combo</button></form><div className="grid gap-3">{items.map((item) => <div key={item.id} className="flex justify-between rounded-2xl border border-white/10 p-4 text-slate-300"><span className="font-semibold text-white">{item.name}</span><span>{item.price.toLocaleString('vi-VN')} đ</span><span>Tồn: {item.stock}</span></div>)}</div></div>;
}
