-- AlterTable
ALTER TABLE `Showtime` ADD COLUMN `couplePrice` INTEGER NOT NULL DEFAULT 160000,
    ADD COLUMN `standardPrice` INTEGER NOT NULL DEFAULT 85000,
    ADD COLUMN `vipPrice` INTEGER NOT NULL DEFAULT 100000;
